checks:
  neutron_dpdk_enabled:
    apt: openvswitch-switch-dpdk
  nova_libvirt_queue_sizes_invalid_config:
    config:
      handler: hotsos.core.plugins.openstack.OpenstackConfig
      path: etc/nova/nova.conf
      assertions:
        not:
          - key: rx_queue_size
            section: libvirt
            ops: [[ge, 1024]]
            allow-unset: false
          - key: tx_queue_size
            section: libvirt
            ops: [[ge, 1024]]
            allow-unset: false
conclusions:
  nova-dpdk-config-not-valid:
    decision:
      - neutron_dpdk_enabled
      - nova_libvirt_queue_sizes_invalid_config
    raises:
      type: OpenstackWarning
      message: >-
        DPDK is enabled but rx_queue_size/tx_queue_size set incorrectly in
        nova.conf (expect both to be >= 1024).
