vars:
  message_pt1: >-
    This node is used for Kubernetes but is not using cpufreq
    scaling_governor in "performance" mode
  message_pt2: >-
    This is not recommended and can result in performance degradation. To fix
    this you can install cpufrequtils, set "GOVERNOR=performance" in
    /etc/default/cpufrequtils and run systemctl restart cpufrequtils.
  message_ondemand: >-
    You will also need to stop and disable the ondemand systemd service in
    order for changes to persist.
  scaling_governor: '@hotsos.core.plugins.kernel.sysfs.CPU.cpufreq_scaling_governor_all'
checks:
  cpufreq_governor_not_performance:
    # can we actually see the setting
    - varops: [[$scaling_governor], [ne, unknown]]
    # does it have the expected value
    - varops: [[$scaling_governor], [ne, performance]]
  kubernetes_installed:
    - snap: kubelet
    # ignore if not running on metal
    - property:
        path: hotsos.core.plugins.system.system.SystemBase.virtualisation_type
        ops: [[eq, null]]
  ondemand_installed_and_enabled:
    systemd:
      ondemand: enabled
conclusions:
  cpufreq-not-performance:
    priority: 1
    decision:
      - cpufreq_governor_not_performance
      - kubernetes_installed
    raises:
      type: KubernetesWarning
      message: >-
        {msg_pt1} (actual={governor}). {msg_pt2}
      format-dict:
        msg_pt1: $message_pt1
        msg_pt2: $message_pt2
        governor: $scaling_governor
  cpufreq-not-performance-with-ondemand:
    priority: 2
    decision:
      - cpufreq_governor_not_performance
      - kubernetes_installed
      - ondemand_installed_and_enabled
    raises:
      type: KubernetesWarning
      message: >-
        {msg_pt1} (actual={governor}). {msg_pt2} {msg_ondemand}
      format-dict:
        msg_pt1: $message_pt1
        msg_pt2: $message_pt2
        msg_ondemand: $message_ondemand
        governor: $scaling_governor
