checks:
  cpufreq_governor_not_performance:
    requires:
      and:
        # can we actually see the setting
        - property:
            path: hotsos.core.plugins.kernel.CPU.cpufreq_scaling_governor_all
            ops: [[ne, unknown]]
        # does it have the expected value
        - property:
            path: hotsos.core.plugins.kernel.CPU.cpufreq_scaling_governor_all
            ops: [[ne, performance]]
  kubernetes_installed:
    requires:
      and:
        - snap: kubelet
        # ignore if not running on metal
        - property:
            path: hotsos.core.plugins.system.SystemBase.virtualisation_type
            ops: [[eq, null]]
  ondemand_installed_and_enabled:
    requires:
      systemd:
        ondemand: enabled
conclusions:
  cpufreq-not-performance:
    priority: 1
    decision:
      and:
        - cpufreq_governor_not_performance
        - kubernetes_installed
    raises:
      type: hotsos.core.issues.KubernetesWarning
      message: >-
        This node is used for Kubernetes but is not using cpufreq
        scaling_governor in "performance" mode (actual={governor}). This is not
        recommended and can result in performance degradation. To fix this you
        can install cpufrequtils, set "GOVERNOR=performance" in
        /etc/default/cpufrequtils and run systemctl restart cpufrequtils.
      format-dict:
        governor: hotsos.core.plugins.kernel.CPU.cpufreq_scaling_governor_all
  cpufreq-not-performance-with-ondemand:
    priority: 2
    decision:
      and:
        - cpufreq_governor_not_performance
        - kubernetes_installed
        - ondemand_installed_and_enabled
    raises:
      type: hotsos.core.issues.KubernetesWarning
      message: >-
        This node is used for Kubernetes but is not using cpufreq
        scaling_governor in "performance" mode (actual={governor}). This is not
        recommended and can result in performance degradation. To fix this you
        can install cpufrequtils, set "GOVERNOR=performance" in
        /etc/default/cpufrequtils and run systemctl restart cpufrequtils. You
        will also need to stop and disable the ondemand systemd service in
        order for changes to persist.
      format-dict:
        governor: hotsos.core.plugins.kernel.CPU.cpufreq_scaling_governor_all

